events/urls.py
from django.urls import include, path

from events.views import *

app_name = 'events'

urlpatterns = [
    path('', EventListView.as_view(), name='list-events'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('fantapoma/', include('fantapoma.urls', namespace='fantapoma')),
]

goscp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('goscp_site.urls')),
    path('fantapoma/', include('fantapoma.urls')),
    path('admin/', admin.site.urls),
    path('fantaplayers/', include('fantaplayers.urls', namespace='fantaplayers')),
    path('events/', include('events.urls', namespace='events')),
]

events/models.py
import uuid

from django.db import models

# from fantapoma.models import Athlete

# Create your models here.


class Athlete(models.Model):
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name


class Club(models.Model):
    SCP = 'PALERMO SC'
    TLMR = 'TELIMAR'
    CCRL = 'LAURIA CCR'
    AUGST = 'AUGUSTA CN'
    ORTG = 'ORTIGIA CC'
    CUS = 'CUS PALERMO'
    PLR = 'PELOROROW'
    UNS = 'UN SICILIANA'
    PRD = 'PARADISO CN'
    THL = 'THALATTA SC'
    MSS = 'MESSINA CN'
    CUSC = 'CUS CATANIA'
    MDLL = 'MONDELLO'
    CRD = 'CARIDDI CC'
    CLUB_CHOICES = [
        (SCP, 'PALERMO SC'),
        (TLMR, 'TELIMAR'),
        (CUS, 'CUS PALERMO'),
        (PLR, 'PELOROROW'),
        (CCRL, 'LAURIA CCR'),
        (AUGST, 'AUGUSTA CN'),
        (ORTG, 'ORTIGIA CC'),
        (UNS, 'UNIONE SICILIANA'),
        (PRD, 'PARADISO CN'),
        (THL, 'THALATTA SC'),
        (MSS, 'MESSINA CN'),
        (CUSC, 'CUS CATANIA'),
        (MDLL, 'MONDELLO'),
        (CRD, 'CARIDDI CC'),
    ]
    name = models.CharField(max_length=50, choices=CLUB_CHOICES)
    athletes = models.ManyToManyField(Athlete, blank=True)

    def __str__(self):
        return self.name


class Event(models.Model):
    url = models.CharField(max_length=200, unique=True, default=uuid.uuid4)
    date = models.DateField()
    location = models.CharField(max_length=80)
    name = models.CharField(max_length=80)
    EVENT_TYPES = [
        ('REG', 'Regionale'),
        ('NAT', 'Nazionale'),
    ]
    type = models.CharField(max_length=80, choices=EVENT_TYPES, default='REG')

    def __str__(self):
        return f"{self.name} {self.location} ({self.date})"


class Race(models.Model):
    number = models.IntegerField(default=0)
    time = models.TimeField(null=True)
    # BOAT_TYPE_CHOICES = [
    #     ('1x', 'Single scull'),
    #     ('2x', 'Double scull'),
    #     ('4x', 'Quadruple scull'),
    #     ('8+', 'Eight'),
    # ]
    boat_type = models.CharField(max_length=20, default='SINGOLO')
    # CATEGORY_CHOICES = [
    #     ('ALLIEVIA1', '7,20 Allievi B1'),
    #     ('JUNIOR', 'Junior'),
    #     ('SENIOR', 'Senior'),
    #     ('MASTERA', 'Master'),
    # ]
    category = models.CharField(max_length=20, default='SENIOR')
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('X', 'Mix'),
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')
    TYPE_CHOICES = [
        ('HEAT', 'Qualificazione'),
        ('FINAL', 'Finale'),
    ]
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, default='FINAL')
    # Number of enrolled crews
    enrolled = models.IntegerField(default=0)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.event} - {self.number}"


class Crew(models.Model):
    bow_number = models.IntegerField(choices=[(i, i) for i in range(1, 9)])
    athletes = models.ManyToManyField(Athlete)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    race = models.ForeignKey(Race, on_delete=models.CASCADE)
    result = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return f"{self.race} - {self.bow_number}"

events/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from .models import *

# Create your views here.


class EventListView(ListView):
    model = Event
    template_name = 'events/event_list.html'
    context_object_name = 'events'


class EventDetailView(DetailView):
    model = Event
    template_name = 'events/event_detail.html'
    context_object_name = 'event'

events/templates/events/event_detail.html
{% extends 'base.html' %}

{% block title %}Eventi{% endblock %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
        <div class="container-fluid p-0">
          <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {{ message }} - <a href={% url 'marketplace' %} class="alert-link">Torna al Marketplace</a>
          </div>
        </div>
        {% endfor %}
    {% endif %}

    <div class="container header text-center mt-5">
        <h1>{{ event.name }}</h1>
        <h2>{{ event.location }} - {{ event.date }}</h2>
    </div>
    <div class="container main mt-5">
        <h2>Programma Gare</h2>
        <div class="container container__races mt-3">
            {% for race in event.race_set.all %}
                <div class="row mt-5">
                    <h5>Gara {{ race.number }} {{ race.boat_type }} {{ race.category }}{{ race.gender }} - Orario: {{ race.time }}</h5>
                    {% for crew in race.crew_set.all %}
                        <div class="col border">
                                <p class="lead d-flex justify-content-between align-items-center">
                                    <span class="badge rounded-pill bg-primary">{{ crew.bow_number }}</span>
                                    {{ crew.club }}
                                </p>
                                <div class="list-group p-2">
                                    {% for athlete in crew.athletes.all %}
                                        <a href="#" class="list-group-item">{{ athlete.name }}</a>
                                    {% endfor %}
                                </div>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

events/templates/events/event_list.html
{% extends 'base.html' %}
{% block title %}Eventi{% endblock title %}

{% block content %}
<div class="container">
    <h2>Eventi</h2>
    <p>Usa questa tabella per inserire i tuoi punteggi ottenuti negli eventi a cui hai partecipato:</p>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Data</th>
                <th scope="col">Manifestazione</th>
                <th scope="col">Risultati</th>
                <th scope="col">Fantapoma</th>
            </tr>
        </thead>
        <tbody>
        {% for event in events %}
          <tr style="transform: rotate(0);">
            <th scope="row">{{ event.date }}</th>
            <td><a href="{% url 'events:event_detail' event.pk %}">{{ event.name }}</a></td>
            <td><a href="{% url 'events:event_detail' event.pk %}" class="btn btn-primary">Vai</a></td>
            <td><a href="{% url 'fantapoma:statistics' %}" class="btn btn-secondary">Vai</a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
</div>
{% endblock content %}