fantaplayers/urls.py
from django.urls import include, path

from fantaplayers.views import ProfileView, UpdateProfile, CreatePlayer

app_name = 'fantaplayers'
urlpatterns = [
        path('', include('django.contrib.auth.urls')),
        path('register', CreatePlayer.as_view(), name='register'),
        path('profile/<str:pk>', ProfileView.as_view(), name='profile'),
        path('update_profile/<str:pk>', UpdateProfile.as_view(), name='update-profile'),
    ]

fantapoma/urls.py
from django.urls import path, include

from . import views
from fantapoma.views import *

app_name = 'fantapoma'

urlpatterns = [
        path('', views.index, name='index'),
        path('mycrew/', MyCrewView.as_view(), name='mycrew'),
        path('marketplace/', FantaAthleteView.as_view(), name='marketplace'),
        path('view_athlete/<int:id>', views.view_athlete, name='view-athlete'),
        path('leaderboard', LeaderboardView.as_view(), name='leaderboard'),
        # path('statistics/', StatisticsView.as_view(), name='statistics'),
        path('view_crew/<str:pk>/', ViewCrew.as_view(), name='view-crew'),
        path('view_crew/', ViewCrew.as_view(), name='view-crew'),
        # Specials
        path('special-market', ListSpecialsView.as_view(), name='special-market'),
        path('buy-special/<int:special_id>/', BuySpecialView.as_view(), name='buy_special'),
        path('sell-special/<int:special_id>/', SellSpecialView.as_view(), name='sell_special'),
        # Aftermatch Points
        path('submit-points/<int:athlete_id>/', UpdatePointsView.as_view(), name='submit-points'),
        path('submit-points/', UpdatePointsView.as_view(), name='submit-points'),
        path('athletes/', RawFantaAthleteListView.as_view(), name='athlete-list'),
        # Utilities
        path('give-points/', GivePointsView.as_view(), name='give-points'),
        path('create-special/', CreateSpecialView.as_view(), name='create-special'),
    ]

goscp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('goscp_site.urls')),
    path('fantapoma/', include('fantapoma.urls')),
    path('admin/', admin.site.urls),
    path('fantaplayers/', include('fantaplayers.urls', namespace='fantaplayers')),
    path('events/', include('events.urls', namespace='events')),
]

fantaplayers/models.py
from django.db import models

# Create your models here.

fantaplayers/forms.py
from django import forms
from django.forms import ModelForm, TextInput, PasswordInput, EmailInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from fantapoma.models import Player, FantaAthlete

class PlayerCreationForm(UserCreationForm):
    team_name = forms.CharField(
        max_length=200, 
        required=True,
        label='Il tuo 8+',)
    fanta_athlete = forms.ModelChoiceField(
        queryset=FantaAthlete.objects.filter(athlete__isnull=True),
        label="Seleziona l'Atleta che ti rappresenta",
        required=False,)

    def __init__(self, *args, **kwargs):
        super(PlayerCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['email'].widget.attrs = {
            'class': 'form-control',
            'aria-describedby': 'emailHelp'
        }
        self.fields['team_name'].widget.attrs = {
            'class': 'form-control',
            'aria-describedby': 'teamNameHelp'
        }
        self.fields['password1'].widget.attrs = {
            'class': 'form-control',
            'aria-describedby': 'passwordHelp'
        }
        self.fields['password2'].widget.attrs = {
            'class': 'form-control',
            'aria-describedby': 'repeatPasswordHelp'
        }

    class Meta:
        model = User
        fields = ('username', 'email', 'team_name', 'fanta_athlete', 'password1', 'password2')

        labels = {
            'username': 'Username',
            'email': 'Indirizzo Email',
            'password1': 'Password',
            'password2': 'Ripeti Password'
        }

    def save(self, commit=True):
        user = super(PlayerCreationForm, self).save()
        team_name = self.cleaned_data['team_name']
        player = Player.objects.create(user=user, team_name=team_name)
        fanta_athlete = self.cleaned_data['fanta_athlete']
        if fanta_athlete is not None:
            fanta_athlete.is_user = player
            fanta_athlete.save()
        else:
            print("No Fanta Athlete selected. Contact the webmaster.")
        return user

fantaplayers/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy

from django.views.generic import DetailView, UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

from django.contrib.auth import login, authenticate

from fantapoma.models import FantaAthlete, Player
from fantaplayers.forms import PlayerCreationForm

# Create your views here.


class CreatePlayer(CreateView):
    model = User
    form_class = PlayerCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('fantapoma:index')

    def form_valid(self, form):
        form.save()
        #authenticate user then login
        username=form.cleaned_data['username']
        password=form.cleaned_data['password1']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        print(f'Form is valid: {form.instance}\n {username} - {password}')
        return redirect(self.success_url)


class ProfileView(LoginRequiredMixin, CreateView):
    model = Player
    fields = ['team_name']
    template_name = 'fantaplayers/profile.html'

    
    def post(self, request, *args, **kwargs):
        cox_id = request.POST.get('cox')
        cox = get_object_or_404(FantaAthlete, id=cox_id)
        request.user.player.cox = cox
        request.user.player.save()
        return HttpResponseRedirect(reverse('fantapoma:mycrew'))




class UpdateProfile(LoginRequiredMixin, UpdateView):
    model = Player
    fields = ['team_name']
    initial = {}

    template_name = 'registration/update_profile.html'
    success_url = reverse_lazy('fantapoma:mycrew')

fantaplayers/templates/fantaplayers/profile.html
{% extends 'base.html' %}

{% block title %}Profile Page{% endblock title %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    {{ message }} - <a href={% url 'marketplace' %} class="alert-link">Torna al Marketplace</a>
  </div>
</div>
{% endfor %}
{% endif %}

<div class="container profile my-5">
    <h1>{{ user.username }}</h1>
    {% if user.true_athlete %}
      <h3 class='text-muted fw-light'>
          <a href={% url 'fantapoma:view-athlete' user.true_athlete.id %} class="text-reset">
              {{ user.true_athlete }}
          </a>
      </h3>
    {% endif %}
    <a href={% url 'fantaplayers:update-profile' user.id %} class='btn btn-info'>Modifica</a>
    <hr>
    <h3>Il tuo 8+</h3>
    <p class="lead">{{ user.player.team_name }}</p>
    <div class="container form-control mb-3" {% if not request.user.athletes_set.count %}disabled{% endif %}>
      <form method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label for="cox" class="form-label">Timoniere</label>
          <select class="form-select" id="cox" name="cox" {% if not user.athletes_set.count %}disabled{% endif %} required>
            {% if user.player.cox %}
              <option value={{ user.player.cox.id }} selected>{{ user.player.cox }}</option>
            {% else %}
              <option value="" selected disabled> Seleziona un timoniere</option>
            {% endif %}
            {% for athlete in user.athletes_set.all %}
              {% if athlete != user.player.cox %}
                <option value="{{ athlete.id }}">{{ athlete.name }}</option>
              {% endif %}
            {% endfor %}
          </select>
        </div>
        <button type="submit" class="btn btn-secondary">Salva</button>
      </form>
    </div>
    <a href={% url 'fantapoma:mycrew' %} class='btn btn-primary'>Visualizza</a>
</div>
{% endblock content %}

{% block footer %}
<footer class="footer mt-auto py-5 bg-light">
  <div class="container-fluid text-left">
    <div class="row justify-content-between">
      <div class="col-5">
        <span class="text-muted">
          Fantapoma - Il gioco del Canottaggio Virtuale
        </span>
      </div>
      <div class="col-5 text-right">
        <span class="text-muted">
          Made by Federico Amato -
          <a href="mailto:fedesss98@hotmail.it" class="text-reset">fedesss98@hotmail.it</a> / 
          <a href="https://www.instagram.com/fedeamat/" class="text-reset">@fedeamat</a> /
        </span>
      </div>
    </div>
  </div>
</footer>
{% endblock %}