events/urls.py
from django.urls import include, path

from events.views import *

app_name = 'events'

urlpatterns = [
    path('', EventListView.as_view(), name='list-events'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('fantapoma/', include('fantapoma.urls', namespace='fantapoma')),
]

fantaplayers/urls.py
from django.urls import include, path

from fantaplayers.views import ProfileView, UpdateProfile, CreatePlayer

app_name = 'fantaplayers'
urlpatterns = [
        path('', include('django.contrib.auth.urls')),
        path('register', CreatePlayer.as_view(), name='register'),
        path('profile/<str:pk>', ProfileView.as_view(), name='profile'),
        path('update_profile/<str:pk>', UpdateProfile.as_view(), name='update-profile'),
    ]

fantapoma/urls.py
from django.urls import path, include

from . import views
from fantapoma.views import *

app_name = 'fantapoma'

urlpatterns = [
        path('', views.index, name='index'),
        path('mycrew/', MyCrewView.as_view(), name='mycrew'),
        path('marketplace/', FantaAthleteView.as_view(), name='marketplace'),
        path('view_athlete/<int:id>', views.view_athlete, name='view-athlete'),
        path('leaderboard', LeaderboardView.as_view(), name='leaderboard'),
        # path('statistics/', StatisticsView.as_view(), name='statistics'),
        path('view_crew/<str:pk>/', ViewCrew.as_view(), name='view-crew'),
        path('view_crew/', ViewCrew.as_view(), name='view-crew'),
        # Specials
        path('special-market', ListSpecialsView.as_view(), name='special-market'),
        path('buy-special/<int:special_id>/', BuySpecialView.as_view(), name='buy_special'),
        path('sell-special/<int:special_id>/', SellSpecialView.as_view(), name='sell_special'),
        # Aftermatch Points
        path('submit-points/<int:athlete_id>/', UpdatePointsView.as_view(), name='submit-points'),
        path('submit-points/', UpdatePointsView.as_view(), name='submit-points'),
        path('athletes/', RawFantaAthleteListView.as_view(), name='athlete-list'),
        # Utilities
        path('give-points/', GivePointsView.as_view(), name='give-points'),
        path('create-special/', CreateSpecialView.as_view(), name='create-special'),
    ]

goscp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('goscp_site.urls')),
    path('fantapoma/', include('fantapoma.urls')),
    path('admin/', admin.site.urls),
    path('fantaplayers/', include('fantaplayers.urls', namespace='fantaplayers')),
    path('events/', include('events.urls', namespace='events')),
]

fantapoma/forms.py
from django import forms
from .models import FantaAthlete, Special, FantaAthleteEventScore

class UpdatePointsForm(forms.ModelForm):
    SPECIAL_ACTIONS = (
        ('cannone', 'Video "A CANNONE" con Ficarra'),
        ('cibo', 'Offrire cibo'),
        ('salto', 'Foto con salto in premiazione'),
        ('selfie', 'Selfie con un Allenatore di Secondo Livello o superiore'),
        ('bevanda', 'Bevanda offerta a un Allenatore di Primo Livello o superiore'),
        ('franchina', 'Selfie con Bruno Franchina'),
        ('batticinque', 'Batticinque a Ficarra'),
        ('vittoria', 'Video "VITTORIA PER LA CANOTTIERI PALERMO" con Vito Scarpello'),
        ('stretta', 'Foto stringendo la mano a un avversario di un altro club'),
        ('calzini', 'Indossare calzini variopinti/spaiati'),
        ('maglietta', 'Indossare una maglietta variopinta'),
        ('occhiali', 'Indossare occhiali da sole'),
        ('cappellino', 'Indossare un cappellino'),
        ('miele', 'Selfie con Miele'),
        ('cazziata', 'Cazziatone da Beni'),
        ('fermars', "Fermarsi prima dell'arrivo"),
        ('ritardo', "Arrivare in ritardo"),
        ('cadere', "Cadere in acqua"),
        ('litigare', "Litigare con un avversario"),
        ('rifiutare', "Rifiutarsi di buttare i rifiuti"),
        ('boe', "Tagliare il traguardo fuori dalle boe"),
        ('sbagliato', "Il giudice in partenza sbaglia il tuo nome"),
        ('ultimo', "Ultimo a gareggiare"),
    )
    golds = forms.IntegerField(label="Medaglie d'Oro", initial=0, required=False)
    silvers = forms.IntegerField(label="Medaglie di Argento", initial=0, required=False)
    bronzes = forms.IntegerField(label="Medaglie di Bronzo", initial=0, required=False)
    lasts = forms.IntegerField(label="Ultimi Posti", initial=0, required=False)
    actions = forms.MultipleChoiceField(
        label='Seleziona le Azioni Speciali che hai compiuto:',
        required=False,
        choices=SPECIAL_ACTIONS, widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = FantaAthlete
        fields = []

    def save(self, commit=True):
        ACTION_POINTS_DICT = {
            'golds': 50,
            'silvers': 30,
            'bronzes': 20,
            'lasts': -10,
            'cannone': 5,
            'cibo': 5,
            'salto': 5,
            'selfie': 5,
            'bevanda': 5,
            'franchina': 5,
            'batticinque': 3,
            'vittoria': 3,
            'stretta': 3,
            'calzini': 3,
            'maglietta': 1,
            'occhiali': 1,
            'cappellino': 1,
            'miele': 1,
            'cazziata': -10,
            'fermarsi': -5,
            'ritardo': -5,
            'cadere': -5,
            'litigare': -5,
            'rifiutare': -2,
            'boe': -2,
            'sbagliato': -1,
            'ultimo': -1,
        }
        race_points = 0
        # Race points
        for position in ['golds', 'silvers', 'bronzes', 'lasts']:
            # Number of first, second, third or last positions
            n = self.cleaned_data[position] or 0
            race_points += ACTION_POINTS_DICT[position] * n
        self.instance.race_points = race_points
        actions_points = sum(
            ACTION_POINTS_DICT[action] for action in self.cleaned_data['actions']
        )
        self.instance.actions_points = actions_points
        return super().save(commit)
    
    
class SpecialForm(forms.ModelForm):
    class Meta:
        model = Special
        fields = ['name', 'special_class', 'special', 'price']


class FantaAthleteEventScoreForm(forms.ModelForm):
    class Meta:
        model = FantaAthleteEventScore
        fields = '__all__'

fantapoma/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from django.views.generic.edit import FormView
from django.db.models import F

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from fantapoma.models import FantaAthlete, Special, Player, FantaAthleteEventScore
from events.models import Crew, Athlete, Race, Event
from django.contrib.auth.models import User
from .forms import UpdatePointsForm, SpecialForm, FantaAthleteEventScoreForm

from django.contrib import messages


MAX_ATHLETES = 9 # Maximum number of athletes to buy


def index(request):
    # return HttpResponse("Fantapoma")
    return render(request, 'fantapoma/index.html', {
        'title': 'Fantapoma: - Il gioco di canottaggio virtuale',
        'nav-home': 'active'})


def view_athlete(request, id):
    fantaathlete = FantaAthlete.objects.get(id=id)
    user = request.user
    if fantaathlete.athlete is not None:
        # All the crews of all the races in which the athlete has participated
        crews = fantaathlete.athlete.crew_set.filter(race__event__date__year=2024) 
    else:
        crews = Crew.objects.none()
    buy = True
    sell = False
    
    # If the user has the athlete in it's eight
    if user.athletes_set.filter(id=fantaathlete.id).exists():
        # Cannot buy, can sell
        buy = False
        sell = True
    # If the user doesn't have the player
    # and doesn't have franchs or doesn't have more space
    elif (user.player.franchs <= 0 
          or user.athletes_set.count() >= MAX_ATHLETES):
        # Cannot buy, cannot sell
        buy = False
        sell = False
    context = {
        'title': f"{fantaathlete.name} - Fantapoma",
        'athlete': fantaathlete,
        'crews': crews,
        'buy': buy,
        'sell': sell,
    }

    if request.method == 'POST':
        """ Prenota atleta """
        if 'acquista' in request.POST:
            franchs = fantaathlete.adjusted_price
            remain_franchs = user.player.franchs - franchs
            if remain_franchs >= 0:
                print('Acquista')
                fantaathlete.players.add(user)
                fantaathlete.save()
                user.player.franchs = remain_franchs
                # Now user cannot buy but can sell
                context['buy'] = False
                context['sell'] = True
                messages.success(request, 'Acquistato!')
            else:
                messages.error(request, 'Non hai abbastanza Franchini per comprare!')
        elif 'rimuovi' in request.POST:
            fantaathlete.players.remove(user)
            franchs = fantaathlete.adjusted_price
            fantaathlete.save()
            user.player.franchs = user.player.franchs + franchs
            # Now user can buy but cannot sell
            context['buy'] = True
            context['sell'] = False
        request.user.player.save()
    return render(request, 'fantapoma/view_athlete.html', context)


class MyCrewView(LoginRequiredMixin, ListView):
    model = FantaAthlete
    template_name = "fantapoma/mycrew.html"

    def get_queryset(self):
        self.user = self.request.user
        return self.user.athletes_set.all()

    def get_context_data(self, **kwargs):
        self.user = self.request.user
        context = super().get_context_data(**kwargs)
        context['atleti'] = self.user.athletes_set.all()
        context['specials'] = self.user.specials_set.all()
        return context



# MARKETPLACE
class FantaAthleteView(ListView):
    template_name = "fantapoma/marketplace.html"
    model = FantaAthlete
    ordering = 'name'

    def get_queryset(self):
        athlete_name = self.request.GET.get('athlete_name')
        queryset = super().get_queryset().order_by('name')
        if athlete_name is not None:
            queryset = FantaAthlete.objects.filter(name__icontains=athlete_name)
        return queryset
    
    def get_ordering(self):
        increasing = self.request.GET.get('increasing', 'off')
        ordering = self.request.GET.get('order', 'name')
        if increasing != 'on':
            ordering = f'-{ordering}'
        return ordering

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.user = self.request.user
        atlethes = self.user.athletes_set.all().values_list('name', flat=True)
        context['atleti'] = list(atlethes)
        context['ordering'] = self.request.GET.get('order', 'name')
        context['increasing'] = self.request.GET.get('increasing', 'off')
        return context


# CLASSIFICA
class LeaderboardView(ListView):
    model = User
    template_name = 'fantapoma/leaderboard.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return sorted(queryset, key=lambda u: u.player.score, reverse=True)

    context_object_name = 'users'


class ViewCrew(DetailView):
    model = User
    template_name = 'fantapoma/view_crew.html'

    context_object_name = 'player'

    def get_object(self):
        pk = self.kwargs.get(self.pk_url_kwarg)
        if pk is None:
            pk = self.request.user.id
            self.kwargs[self.pk_url_kwarg] = pk
        return super(ViewCrew, self).get_object()         

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get(self.pk_url_kwarg)
        if pk is None:
            pk = self.request.user.id

        context['athletes'] = FantaAthlete.objects.filter(players__pk=pk)
        return context



class ListSpecialsView(ListView):
    template_name = "fantapoma/special_market.html"
    model = Special


class RawFantaAthleteListView(ListView):
    model = FantaAthlete
    template_name = 'fantapma/athlete_list.html'


class UpdatePointsView(LoginRequiredMixin, FormView):
    template_name = 'fantapoma/submit_points.html'
    form_class = UpdatePointsForm
    success_url = reverse_lazy('leaderboard')

    def handle_no_permission(self):
        # Update an error message befor redirecting
        messages.error(self.request, 'Devi fare il login prima di aggiungere il tuo punteggio')
        return super().handle_no_permission()

    def get_context_data(self, **kwargs):
        # Update the context data to serve the name of the athlete selected by URL ID
        context = super().get_context_data(**kwargs)
        if athlete_id := self.kwargs.get('athlete_id'):
            athlete = FantaAthlete.objects.get(id=athlete_id)
            context['athlete'] = athlete.name
        return context

    def get_form_kwargs(self):
        # Takes the user athlete or one athlete with ID specified in the URL 
        kwargs = super().get_form_kwargs()
        if athlete_id := self.kwargs.get('athlete_id'):
            athlete = FantaAthlete.objects.get(id=athlete_id)
        else:
            athlete = self.request.user.true_athlete
        kwargs['instance'] = athlete
        return kwargs

    def form_valid(self, form):
        # Save the updated model
        # form.instance = self.request.user.athlete
        form.save()
        return super().form_valid(form)


class EventsView(TemplateView):
    template_name = 'fantapoma/../events/templates/events/events.html'


class StatisticsView(TemplateView):
    template_name = 'fantapoma/statistics.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        top_athletes = FantaAthlete.objects.annotate(
            points_sum=F('race_points') + F('actions_points')
        ).order_by('-points_sum')[:5]
        top_race_athletes = FantaAthlete.objects.order_by('-race_points')[:5]
        top_actions_athletes = FantaAthlete.objects.order_by('-actions_points')[:5]
        context['best_athlete'] = top_athletes[0] 
        context['top_athletes'] = top_athletes
        context['race_points'] = [athlete.race_points for athlete in top_athletes]
        context['actions_points'] = [athlete.actions_points for athlete in top_athletes]
        context['top_race_athletes'] = top_race_athletes
        context['top_actions_athletes'] = top_actions_athletes
        return context


class GivePointsView(UserPassesTestMixin, View):
    template_name = 'fantapoma/give_points.html'

    def test_func(self):
        return self.request.user.is_staff

    def get(self, request, *args, **kwargs):
        players = Player.objects.select_related('user').all()
        print(players)
        return render(request, self.template_name, {'players': players})

    def post(self, request, *args, **kwargs):
        usernames = request.POST.getlist('users')
        franchs = int(request.POST.get('franchs')) if request.POST.get('franchs') else 0
        Player.objects.filter(user__username__in=usernames).update(franchs=F('franchs') + franchs)
        players = Player.objects.select_related('user').all()
        return render(request, self.template_name, {'players': players})


class CreateSpecialView(UserPassesTestMixin, CreateView):
    model = Special
    form_class = SpecialForm
    template_name = 'fantapoma/create_special.html'
    success_url = reverse_lazy('fantapoma:create-special')

    def test_func(self):
        return self.request.user.is_staff
    

class BuySpecialView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        special = get_object_or_404(Special, id=kwargs['special_id'])
        franchs = special.price
        remain_franchs = request.user.player.franchs - franchs
        if special.players.filter(id=request.user.id).exists():
            messages.error(request, 'Hai già acquistato questo Special!')   
        elif remain_franchs < 0:
            messages.error(request, 'Non hai abbastanza Franchini per comprare!')
        else:

fantapoma/templates/fantapoma/leaderboard.html
{% extends 'base.html' %}
{% block title %}Classifica{% endblock title %}

{% block content %}
<div class="container">
    <h2>Classifica</h2>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Giocatore</th>
                <th scope="col">8+</th>
                <th scope="col">Punteggio</th>
            </tr>
        </thead>
        <tbody>
          {% for user in users %}
          <tr style="transform: rotate(0);">
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ user }}</td>
            <td ><a href="{% url 'fantapoma:view-crew' user.id %}" class="stretched-link">{{ user.player.team_name }}</a></td>
            <td>{{ user.player.score }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
</div>
{% endblock content %}

{% block footer %}
<footer class="footer mt-auto py-5 bg-light text-center">
  <div class="container-fluid text-left">
    <div class="row justify-content-between">
      <div class="col-4">
        <span class="text-muted">
          Fantapoma - Il gioco del Canottaggio Virtuale
        </span>
      </div>
      <div class="col-8 text-right">
        <span class="text-muted">
          Made by Federico Amato -
          <a href="mailto:fedesss98@hotmail.it" class="text-reset">fedesss98@hotmail.it</a> / 
          <a href="https://www.instagram.com/fedeamat/" class="text-reset">@fedeamat</a> /
        </span>
      </div>
    </div>
  </div>
</footer>
{% endblock footer %}

fantapoma/templates/fantapoma/marketplace.html
{% extends "base.html" %}

{% block title %}Marketplace{% endblock %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    {{ message }} - <a href={% url 'fantapoma:marketplace' %} class="alert-link">Torna al Marketplace</a>
  </div>
</div>
{% endfor %}
{% endif %}

<style>
@media (max-width: 992px) {

  .col-sm-4 {
    flex: 0 0 100%;
    max-width: 100%;
    padding: 0 2rem;
  }
}

@media (max-width: 450px) {

  .col-sm-4 {
    padding: 0;
  }
}

  
</style>

<div class="container header text-center mt-5">
  <h1>MARKETPLACE</h1>
  <h2>Prenota i tuoi Atleti</h2>
</div>
<div class="container card-container mt-5">
  <h3>Atleti</h3>
  <form action="" method="GET" class="form-floating mb-3">
    <div class="row g-3 my-2">
      <div class="col-sm-7">
        <input type="search" name="athlete_name" id="searchAthlete" class="form-control" placeholder="Ricerca Atleta">
      </div>
      <div class="col-auto">
        <input type="submit" value="Ricerca" class="btn btn-primary">
      </div>
    </div>
    <div class="row g-3 my-2">
      <div class="col-sm-2">Ordina per:</div>
      <div class="col-sm-3">
        <select name="order" id="order" class="form-control">
          <option value="name" {% if ordering == 'name' or ordering is None %}selected{% endif %}>
            Nome
          </option>
          <option value="points" {% if ordering == 'points' %}selected{% endif %}>
            Punteggio
          </option>
          <option value="first" {% if ordering == 'first' %}selected{% endif %}>
            Primi Posti
          </option>
          <option value="second" {% if ordering == 'second' %}selected{% endif %}>
            Secondi Posti
          </option>
          <option value="third" {% if ordering == 'third' %}selected{% endif %}>
            Terzi Posti
          </option>
          <option value="total" {% if ordering == 'total' %}selected{% endif %}>
            Totale Gare
          </option>
        </select>
      </div>
      <div class="col-sm-2 py-1">
        <div class="form-check form-switch">
          <input class="form-check-input" type="checkbox" name="increasing" role="switch" id="orderType" {% if increasing == 'on' %}checked{% endif %}>
          <label class="form-check-label" for="orderType">Crescente</label>
        </div>
      </div>
      <div class="col-sm-1">
        <input type="submit" value="Ordina" class="btn btn-primary">
      </div>
    </div>
  </form>
  <p></p>
  <div class="container-fluid object">
    <div class="row">
    {% for object in object_list %}
      <div class="col-sm-4 my-3">
        <div class="card shadow">
          <div class="card-header">
            <h5>{{object.name}}</h5>
          </div>
          <div class="card-body">
            <ul class="list-group list-group-numbered">
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">Primi Posti:</div>
                <span class="badge bg-primary rounded-pill">{{object.first}}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">Secondi Posti:</div>
                <span class="badge bg-primary rounded-pill">{{object.second}}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">Terzi Posti:</div>
                <span class="badge bg-primary rounded-pill">{{object.third}}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">Totale Gare:</div>
                <span class="badge bg-primary rounded-pill">{{object.total}}</span>
              </li>
            </ul>
            <h5 class="card-text text-end m-2">{{object.adjusted_price}} Franchini</h5>
            <a href="{% url 'fantapoma:view-athlete' object.id %}" class="btn btn-primary">Vedi</a>
          </div>
          <div class="card-footer text-muted">
            Prenotato da {{ object.bookings }} Giocatori.
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</div>
  
{% endblock %}

fantapoma/templates/fantapoma/mycrew.html
{% extends "base.html" %}

{% block title %}My crew{% endblock %}

{% block content %}
<div class="container header text-center mt-5">
  <h2>{{ request.user.player.team_name }}</h2>
  <h3 class="text-muted fw-light fs-4">{{ request.user.username }}</h3>
</div>
{% if request.user.player.cox is not None %}
  <div class="container mt-3 border-top border-bottom">
    <h3 class="pt-3">Timoniere:</h3>
    <p>{{request.user.player.cox}}</p>
  </div>
{% else %}
  <div class="container mt-3 border-top border-bottom">
    <p class="pt-3"><em>Seleziona un Timoniere dalla tua pagina del Profilo!</em></p>
  </div>
{% endif %}
<div class="container card-container mt-2">
  <h3 class="text-center">I tuoi Fanta Atleti</h3>
  <div class="container-fluid object">
    <div class="row">
    {% for object in atleti %}
      <div class="col-sm-4 my-3">
        <div class="card shadow">
          <div class="card-header">
            <h5>{{object.name}}</h5>
          </div>
          <div class="card-body">
            <p class="card-text">Ha gareggiato a Poma dal {{object.first_time|date:'d/m/Y'}} fino al {{object.last_time|date:'d/m/Y'}}</p>
            <ul class="list-group list-group-numbered">
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">Primi Posti:</div>
                <span class="badge bg-primary rounded-pill">{{object.first}}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">Secondi Posti:</div>
                <span class="badge bg-primary rounded-pill">{{object.second}}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">Terzi Posti:</div>
                <span class="badge bg-primary rounded-pill">{{object.third}}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">Totale Gare:</div>
                <span class="badge bg-primary rounded-pill">{{object.total}}</span>
              </li>
            </ul>
            <h5 class="card-text text-end m-2">{{ object.adjusted_price }} Punti</h5>
            <a href="{% url 'fantapoma:view-athlete' object.id %}" class="btn btn-primary">Vedi</a>
          </div>
          <div class="card-footer text-muted">
            Prenotato da {{ object.bookings }} Giocatori.
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</div>
<div class="container card-container mt-5">
  <h3 class="text-center">I tuoi Special</h3>
  <div class="container-fluid object">
    <div class="row">
    {% for object in specials %}
      <div class="col-sm-4 my-3">
        <div class="card shadow">
          <div class="card-header">
            <h5>{{object.name}}</h5>
          </div>
          <div class="card-body">
            <p class="card-text">{{ object.special }}</p>
            <h5 class="card-text text-end m-2">{{object.price}} Franchini</h5>
            <a href="{% url 'fantapoma:sell_special' object.id %}" class="btn btn-danger">Rimuovi</a>
          </div>
          <div class="card-footer text-muted">
            Special di tipo {{ object.tipo }}.
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</div>


<style>
  @media (max-width: 992px) {
  
    .col-sm-4 {
      flex: 0 0 100%;
      max-width: 100%;
      padding: 0 2rem;
    }
  }
  
  @media (max-width: 450px) {
  
    .col-sm-4 {
      padding: 0;
    }
  }
  
    
  </style>

{% endblock %}

fantapoma/templates/fantapoma/navbar.html
{% block navbar %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'fantapoma:index' %}">Fantapoma</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'fantapoma:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fantapoma:leaderboard' %}">Classifica</a>
        </li>
        {% comment %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'events:list-events' %}">Eventi</a>
          </li>
        {% endcomment %}
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fantapoma:marketplace' %}">Marketplace</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fantapoma:special-market' %}">Special Market</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fantapoma:mycrew' %}">My Crew</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fantaplayers:profile' request.user.id %}">Profilo</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'fantaplayers:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fantaplayers:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href={% url 'fantaplayers:register' %}>Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% if request.user.is_authenticated %}
<nav class="nav justify-content-center">
  <span class="navbar-text">
    {{ request.user|title }}, hai ancora {{ request.user.player.franchs }} Franchini e 
    {{ request.user.athletes_set.count }} atleti <a href={% url 'fantapoma:mycrew' %}>nel tuo Otto</a>.
  </span>
</nav>
{% endif %}

{% endblock %}

fantapoma/templates/fantapoma/set_score.html
{% extends 'base.html' %}

{% block title %}Assegna il Punteggio a un Fanta Atleta{% endblock title %}

{% block content %}
<div class="container">
    <h2>Assegna il Punteggio a un Fanta Atleta</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Assegna">
    </form>